---
title: "slides"
output:
  xaringan::moon_reader:
    css: ["default", "css/xaringan-themer.css"]
    self_contained: false
    lib_dir: libs
    nature:
      ratio: "16:9"
    seal: false
---

# STAT 436: Statistical Data Visualization

## Spring 2023

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  dpi = 200,
  fig.align = "center",
  out.width = 650,
  fig.height = 3,
  fig.width = 9
  )
th <- theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(th)
options(width = 100)
```

---


### Welcome!!

I'm excited to share this course with you this semester. There are few
activities that engage creative, quantitative, and critical thinking skills all
at once, but data visualization is one of them.

Nothing makes my day like a good data visualization, and I look forward to
seeing those that you create.

---

### Syllabus

* Learning outcomes
* Teaching team and office hours
* Assessments
* Grading

---

### Learning Outcomes

1.	Develop a vocabulary of visual encodings that support exploration of
geospatial, temporal, tree-structured, and network data, and demonstrate
facility implementing them using packages in the R programming language.
1.	Design dynamic queries that support interactive visualization of
heterogeneous data, and demonstrate facility implementing them using the shiny
package in the R programming language.
1.	Design effective visualizations to summarize the results of dimensionality
reduction and clustering algorithms.

---

### Learning Outcomes

1.	Use visual artifacts derived from complex statistical and machine learning
models to discuss the patterns they learn and mistakes they make.
1.	Evaluate strengths and weaknesses of visualizations in relation to the tasks
they support.

---


### Office Hours

.pull-left[
We will announce in-person and virtual office hours depending on the results of
this poll:  https://go.wisc.edu/828r85
]

---


### Assessments

* In-class exercises and discussions
* 4 Portfolio assignments
* 3 group project reports and 1 presentation
  - Teams of 4 - 5 people
* 1 midterm exam

---

### Grading

* In-Class Exercises: 15%
* Midterms: 20%
* Personal Portfolio: 35%
* Group Project: 25%

---

### Class Resources

1. [Canvas page](https://canvas.wisc.edu/courses/346654/modules)
  - Links to all other resources
1. [Readings](https://github.com/krisrs1128/stat436_s23/raw/main/logistics/syllabus.docx) (Page 3)
1. [Piazza](https://canvas.wisc.edu/courses/346654/external_tools/65)
1. [Exercises](https://canvas.wisc.edu/courses/321152/files/27094119?module_item_id=5161970)
1. [Online notes](https://krisrs1128.github.io/stat436_s23/)
1. [Online recordings](https://mediaspace.wisconsin.edu/) (also linked in notes)
1. [Worked code examples](https://github.com/krisrs1128/stat436_s23/) (also linked in notes)

---

### Questions?

Also feel free to speak with me after class.

---

### Exercise 0.1

1. Introduce yourself to the people sitting at your table. Your name, program,
and one thing most people don't know about you.

1. Submit a response to [Formulating Questions] in the exercise sheet.

1. Share your chosen datasets in groups of 2 - 3 people.

[Formulating Questions] Pick a dataset from
[TidyTuesday](https://github.com/rfordatascience/tidytuesday#datasets), [Data Is
Plural](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0),
[Kaggle Datasets](https://www.kaggle.com/datasets), [Google Dataset
Search](https://datasetsearch.research.google.com/), or your own personal
studies that you would like to visualize this semester. What makes you
interested in this dataset? Please provide a link, so we can use it to create
future exercises.

---

## January 26, 2023

---

## January 31, 2023

---

## February 2, 2023

---

## February 7, 2023

---

## February 9, 2023

---

## February 14, 2023

---

## February 16, 2023

---

## February 21, 2023

---

## February 23, 2023

---

## February 28, 2023

---

## March 2, 2023

---

## March 7, 2023

---

## March 9, 2023

---

## March 21, 2023

---

## March 23, 2023

